import { CiCircleFilled } from "@ant-design/icons";
import { Button, DatePicker, Space } from "antd";
import Head from "next/head";
import React from "react";

import styles from "@/styles/Home.module.css";

export default function Home() {
  const onChange = () => {};

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ padding: 100 }}>
        <Space direction="vertical">
          <Button type="primary">Primary Button</Button>
          <Button type="ghost">Ghost Button</Button>
          <DatePicker onChange={onChange} />
          <CiCircleFilled />
        </Space>
      </div>
    </div>
  );
}
